DROP TABLE IF EXISTS daily_summary CASCADE;
DROP TABLE IF EXISTS article CASCADE;

CREATE TABLE daily_summary (
                               id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               date DATE NOT NULL UNIQUE,
                               summaries JSONB,
                               categories JSONB
);

CREATE TABLE article (
                         id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         url VARCHAR(500) NOT NULL,
                         published_at TIMESTAMPTZ,
                         title TEXT,
                         description TEXT,
                         source VARCHAR(30),
                         categories JSONB,
                         category VARCHAR(20) DEFAULT '',

                         daily_summary_id INT REFERENCES daily_summary(id)
);

CREATE OR REPLACE FUNCTION get_summary_references(p_summary_id INT)
    RETURNS JSONB LANGUAGE sql STABLE AS '
    SELECT
        jsonb_object_agg(source, categories_data)
    FROM (
             SELECT
                 source,
                 jsonb_object_agg(category, items) as categories_data
             FROM (
                      SELECT
                          source,
                          category,
                          jsonb_agg(id::text || '' - '' || coalesce(title, '''')) AS items
                      FROM article
                      WHERE daily_summary_id = p_summary_id
                      GROUP BY source, category
                  ) inner_sub
             GROUP BY source
         ) outer_sub;
';

CREATE OR REPLACE VIEW view_daily_summary AS
SELECT
    id AS summary_id,
    date,
    summaries,
    categories,
    get_summary_references(id) AS "references"
FROM daily_summary
WHERE get_summary_references(id) IS NOT NULL;